cloudgate:
  required_version: ">= 2.6"
app:
  name: perfbot
  environment: beta
  region: us-west-2
  vpc_cluster: eng
  deploy_group: PerfbotDeployers
  deploy_users: [jmadsen]
  ssh_users:
    jmadsen: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6vZNy7nW59G0lK1GM/0BZAaNlfAAjDnAX9ysHOg0uhUi+XtE0seG36ej24DscXYLgE22xlOvYSS/jDtUiW+JYztz9wZ/HetiY/g9oKy4GCD0OWjE3DAi0+it9krdJkqDEXVstjbkex2DpG0qmUStUGIlenBYWc0GofDYUo6NqVTRnTACnKiCV96HofxjakHzBF1vu95oe0itDPIoOyxP7zgm8f64DkSPNxP6elRnizZtaFBtHqPle8iCponZ3p9LpdryQdvmO4vIenvGZljCwA07+nbL8Os2SleQYTH4JD3ENiioQIbDzAfsSv1zfuVLgcA3xMuFEADiAQaVrL6eN
  deploy:
    docker_registry: docker.insops.net
  exposed_port: 9000
  instance_pools:
    web:
      flavor: web
      health_check_path: /health_check
      ssl_cert_arn: "arn:aws:iam::830473435438:server-certificate/star.inseng.net_20160531"
      min_size: 1
      max_size: 1
      instance_type: t2.small
      env_vars:
        PERFBOT_ROLE: web
  cache:
    cache_node_type: cache.t2.micro
    num_cache_nodes: 1
    env_var_prefix: REDIS
  env_vars:
    NODE_ENV: "production"
    EXPRESS_PORT: "9000"
    HUBOT_GRAFANA_URL: "https://grafana.insops.net"
    HUBOT_GLINK_HOSTNAME: "graphite.insops.net"
    HUBOT_GLINK_USE_SLACK_API: 'true'
    HUBOT_GLINK_SLACK_IMAGES: 'true'
    HUBOT_GLINK_SLACK_COLOR: "#34495E"
    HUBOT_GLINK_ABSOLUTE_TIMES: "true"
    HUBOT_GLINK_DEFAULT_PARAMS: "from:-4d, until:now, width:750, height: 450, drawNullAsZero:true, bgcolor:black, fgcolor:white, template:grafana, tz:America/Denver"
    HUBOT_GLINK_DEFAULT_APP: 'canvas'
    HUBOT_GLINK_CANVAS_TEMPLATE: "stats.timers.canvas.prod.request.!!#controller#!!.!!#action#!!.!!#type#!!.!!#stat#!!"
    HUBOT_GLINK_CANVAS_TEMPLATE_DEFAULTS: "!!#controller#!!===users, !!#action#!!===index, !!#type#!!===total, !!#stat#!!==={mean,median,upper_95}"
    HUBOT_GLINK_PANDASH_TEMPLATE: "stats.timers.cg.pandash.beta.request.!!#controller#!!.!!#action#!!.!!#type#!!.!!#stat#!!"
    HUBOT_GLINK_PANDASH_TEMPLATE_DEFAULTS: "!!#controller#!!===api-v1-apps, !!#action#!!===show, !!#type#!!===total, !!#stat#!!==={mean,median,upper_95}"
    HUBOT_GLINK_CATALOG_TEMPLATE: "stats.timers.ins-app.catalog.production.request.!!#controller#!!.!!#action#!!.!!#type#!!.!!#stat#!!"
    HUBOT_GLINK_CATALOG_TEMPLATE_DEFAULTS: "!!#controller#!!===enrollment, !!#action#!!===create, !!#type#!!===total, !!#stat#!!==={mean,median,upper_95}"
    HUBOT_GLINK_SIS_APP_TEMPLATE: "stats.timers.sis_app.production.request.!!#controller#!!.!!#action#!!.!!#type#!!.!!#stat#!!"
    HUBOT_GLINK_SIS_APP_TEMPLATE_DEFAULTS: "!!#controller#!!===agent_files, !!#action#!!===create, !!#type#!!===total, !!#stat#!!==={mean,median,upper_95}"
    HUBOT_GLINK_ZUULEDGE_TEMPLATE: "stats.timers.cg.zuul.edge.request.!!#controller#!!.!!#action#!!.!!#type#!!.!!#stat#!!"
    HUBOT_GLINK_ZUULEDGE_TEMPLATE_DEFAULTS: "!!#controller#!!===api-roles, !!#action#!!===index, !!#type#!!===total, !!#stat#!!==={mean,median,upper_95}"
    HUBOT_GLINK_ZUUL_TEMPLATE: "stats.timers.cg.zuul.prod.request.!!#controller#!!.!!#action#!!.!!#type#!!.!!#stat#!!"
    HUBOT_GLINK_ZUUL_TEMPLATE_DEFAULTS: "!!#controller#!!===api-roles, !!#action#!!===index, !!#type#!!===total, !!#stat#!!==={mean,median,upper_95}"
    HUBOT_GLINK_BRIDGE_TEMPLATE: "stats.timers.cg.bridge.prod.request.!!#controller#!!.!!#action#!!.!!#type#!!.!!#stat#!!"
    HUBOT_GLINK_BRIDGE_TEMPLATE_DEFAULTS: "!!#controller#!!===api-author-roles, !!#action#!!===create, !!#type#!!===total, !!#stat#!!==={mean,median,upper_95}"
    HUBOT_GLINK_DREDD_TEMPLATE: "stats.timers.cg.dredd.prod.request.!!#controller#!!.!!#action#!!.!!#type#!!.!!#stat#!!"
    HUBOT_GLINK_DREDD_TEMPLATE_DEFAULTS: "!!#controller#!!===problems, !!#action#!!===sidebar, !!#type#!!===total, !!#stat#!!==={mean,median,upper_95}"
    HUBOT_GLINK_TWEED_TEMPLATE: "stats.timers.cg.tweed.production.request.!!#controller#!!.!!#action#!!.!!#type#!!.!!#stat#!!"
    HUBOT_GLINK_TWEED_TEMPLATE_DEFAULTS: "!!#controller#!!===tweed_auth-sessions, !!#action#!!===show, !!#type#!!===total, !!#stat#!!==={mean,median,upper_95}"
    HUBOT_GLINK_COMMONS_TEMPLATE: "stats.timers.ins-app.lor-production.us-east-1.requests.!!#controller#!!.!!#action#!!.!!#type#!!.!!#stat#!!"
    HUBOT_GLINK_COMMONS_TEMPLATE_DEFAULTS: "!!#controller#!!===Courses, !!#action#!!===index, !!#type#!!===total, !!#stat#!!==={mean,median,upper_95}"
